### ISSUE TITLE
preprocess_cancellation.exe does not exist

### ISSUE THREAD

**Issue by xbk666** [kageurufu/preprocess_cancellation#11]
Using a superslicer on Windows 10 however preprocess_cancellation.exe does not exists. The slicer failed to execute the postprocessing script

**Comment by AustinTylerDean** [comment]
I get it, it's embarrassing when you find the solution to your question that seemed ridiculous that you didn't solve earlier...

But here I am asking the same question.

Why is there mention of an executable file when there isn't one in the code?

I've tried to get selective cancellation figured out, and for some reason it's not happening, so I followed some links here to try it another way.

Could someone assist an old DOS/Windows guy installing this with Prusaslicer and Win11?

**Comment by EU4AX** [comment]
On the example of prusaslicer
preprocess_cancellation.exe must be placed in same directory as prusa-slicer.exe file. Also, the following settings should be made
![2023-07-10_21-02](https://github.com/kageurufu/preprocess_cancellation/assets/110179796/4a375f44-270b-4d93-be95-8fca65e5660f)

**Comment by AustinTylerDean** [comment]
Where is the executable file? Is it already included from the slicer software or does it come from this project? If it does, where is it in this project? I just don't see it on the code listing.

I really appreciate you responding, @EU4AX you get 1,000 kudos for replying to a closed thread!

**Comment by EU4AX** [comment]
Here, if I understood your problem correctly
https://github.com/kageurufu/preprocess_cancellation/releases/tag/0.3.a2
![2023-07-11_22-35](https://github.com/kageurufu/preprocess_cancellation/assets/110179796/dbd637b8-75f1-4054-89da-9fa46cc35765)

**Comment by AustinTylerDean** [comment]
> Here, if I understood your problem correctly https://github.com/kageurufu/preprocess_cancellation/releases/tag/0.3.a2 ![2023-07-11_22-35](https://user-images.githubusercontent.com/110179796/252774488-dbd637b8-75f1-4054-89da-9fa46cc35765.jpg)

You did! Thank you! I've never had to click over there before if you can believe that!

Thanks so much for your time today!
